version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: foroarriz-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foroarriz
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
